# Generated by Django 3.2.8 on 2021-10-18 02:46

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=shop.models.path_and_rename, verbose_name='主要圖片'),
        ),
    ]
